/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import irc.Connection;
import irc.Message;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.KeyStroke;
/**
 *
 * @author stapl
 */
public class View extends javax.swing.JPanel {
    Connection connection;
    /**
     * Creates a channel view panel
     */
    public View(Connection connection) {
        initComponents();
        this.connection = connection;
        jTextArea1.getDocument().putProperty("filterNewlines", Boolean.TRUE);
        jTextArea1.setVisible(false);
        jTextArea2.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n");
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setNextFocusableComponent(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    /** Adds a message to the channel
     * 
     */
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        if(KeyStroke.getKeyStrokeForEvent(evt) == KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0)){
            if(connection.getChannel()!=null){
                connection.addMessage(new Message(jTextArea1.getText().replaceAll("\n","")+"\n\n", connection.getUser()));
                jTextArea1.selectAll();
                jTextArea1.replaceSelection("");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed
    /** Initializes the text for the home window
     * 
     */
    public void setText(){
        jTextArea2.selectAll();
        if(connection.getChannel()==null){
            jLabel2.setText("Home");
            jScrollPane1.setVisible(false);
            jScrollPane2.setVisible(false);
            jTextArea1.setVisible(false);
            jTextArea2.setVisible(false);
            return;
        } 
        
        jLabel2.setText(connection.getChannel().getName());
        if (connection.getChannel().getMessages().isEmpty()){
            jTextArea2.replaceSelection("");
            return;
        }
        for(Message message:connection.getChannel().getMessages()){
            jTextArea2.replaceSelection(message.toString());
        }
        jTextArea1.setVisible(true);
        jTextArea2.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(true);
        repaint();
    }
    /** Updates the text when a new message is added
     * 
     * @param message the message to add
     */
    public void updateText(Message message){
        jTextArea2.replaceSelection(message.toString());
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

}
